### 1. Count numbers
Use a for statement to count from:

  a)   -10 to 10 with one increment (*)
  
  b)   -10 to 10 with two increment (*)

In [15]:
for i in range(-10,11): # start, stop, step
    print(i, "\t", end='') #  \t = tab

-10 	-9 	-8 	-7 	-6 	-5 	-4 	-3 	-2 	-1 	0 	1 	2 	3 	4 	5 	6 	7 	8 	9 	10 	

In [17]:
for i in range(-10,11,2):   # start, stop, step
    print(i, "\t", end='') #  \t = tab

-10 	-8 	-6 	-4 	-2 	0 	2 	4 	6 	8 	10 	

### 2. Arithmetic sum

a) sum = 1 + 2 (...) + 99 + 100

b) sum = 1 + 3 (...) +97 +  99

In [39]:
b = 0
for a in range(1,101):
   b += a
   
print(b)

5050


In [40]:
b = 0
for a in range(1,101,2):
   b += a
   
print(b)

2500


### 3. Multiplication table 
Use for statement(s) to:

  a)   print out the 6th multiplication table from 0 to 10 (*)

  b)   let the user input the table, start and end of the table. (*)

  c)   print out a full multiplication table from 0 to 10. (**)

In [27]:
#a) 
for i in range(11):
    print(f"{6 * i}"," ", end='')

0  6  12  18  24  30  36  42  48  54  60  

''

In [53]:
#b) Using functions. Probably very redundant but fun to make.

def getinput(t) -> int:
    val = input(int(input(f"{t}")))
    a = int(val)
    return a

def func():
    number = getinput("Select number:")
    start = getinput("Start:")
    stop = getinput("Stop:")
    for i in range(start , (1 + stop)):
        print(f"{number*i} ", end ="")
    print(f"\n Table {start=}, User {number=}, User {stop=}")

func()

8 16 24 32 40 48 56 64 72 80 88 96 104 112 120 128 
 Table start=1, User number=8, User stop=16


In [65]:
#c) Using NumPy for fun.
import numpy as np

row = np.arange(11)
for i in row:
    print (i*row)


[0 0 0 0 0 0 0 0 0 0 0]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0  3  6  9 12 15 18 21 24 27 30]
[ 0  4  8 12 16 20 24 28 32 36 40]
[ 0  5 10 15 20 25 30 35 40 45 50]
[ 0  6 12 18 24 30 36 42 48 54 60]
[ 0  7 14 21 28 35 42 49 56 63 70]
[ 0  8 16 24 32 40 48 56 64 72 80]
[ 0  9 18 27 36 45 54 63 72 81 90]
[  0  10  20  30  40  50  60  70  80  90 100]


numpy.arange creates arrays with regularly incrementing values, so it's very useful above. However the output could look neater. Maybe plot it with pyplot?